;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://beford.bitrix24.eu/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"398","sec":"je26oh","lang":"ua","address":"https:\/\/beford.bitrix24.eu","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":5}},"data":{"language":"ua","design":{"font":{"uri":"","family":"var(--landing-font-family)"},"border":{"bottom":false,"top":false,"left":false,"right":false},"color":{"primary":"#ffd770ff","primaryText":"#000000ff","text":"#000000ff","background":"#ffffffff","fieldBorder":"#0000000c","fieldBackground":"#0000000c","fieldFocusBackground":"#ffffffff"}},"title":"","desc":"","buttonCaption":"\u0417\u0410\u041c\u041e\u0412\u0418\u0422\u0418\u00a0","useSign":false,"date":{"dateFormat":"DD.MM.YYYY","dateTimeFormat":"DD.MM.YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"EUR","title":"\u0415\u0432\u0440\u043e","format":"# \u0026euro;"},"fields":[{"id":"LEAD_NAME","name":"LEAD_NAME","label":"\u0406\u043c\u0027\u044f","visible":true,"required":true,"multiple":false,"type":"name","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_PHONE","name":"LEAD_PHONE","label":"\u0422\u0435\u043b\u0435\u0444\u043e\u043d","visible":true,"required":true,"multiple":false,"type":"phone","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null}],"agreements":[],"dependencies":[],"recaptcha":{"use":false}}},"resources":{"app":"https:\/\/cdn.bitrix24.eu\/b25124729\/crm\/form\/app.js","polyfill":"https:\/\/cdn.bitrix24.eu\/b25124729\/crm\/form\/polyfill.js"}});
})();


})();